spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    #url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
#  rabbitmq:
#    username: guest
#    password: guest
#    host: 192.168.56.101
#    publisher-confirms: true
#    publisher-returns: true
#  redis:
#    host: 192.168.56.101
#    database: 0
#    port: 6379
    #password: 123
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
logging:
  level:
    #org.javaboy.vhr.mapper: debug
    com.example.demo.dao: debug
fastdfs:
  nginx:
    host: http://192.168.91.128/

